"""add daily gaming limit

Revision ID: 4c2290137572
Revises: b7e41e5af904
Create Date: 2026-08-14 12:33:57.615642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2290137572'
down_revision: Union[str, Sequence[str], None] = 'b7e41e5af904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_gaming_limit_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_gaming_limit_minutes')
    # ### end Alembic commands ###
