"""add steam tracking

Revision ID: f3c8096926fa
Revises: ad09f09b833e
Create Date: 2026-08-11 11:51:07.997568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c8096926fa'
down_revision: Union[str, Sequence[str], None] = 'ad09f09b833e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_tracking_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_app_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(length=255), nullable=False),
    sa.Column('playtime_minutes', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discord_user_id'], ['users.discord_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_user_id', 'steam_app_id', name='uq_steam_tracking_user_game')
    )
    op.create_index(op.f('ix_steam_tracking_states_discord_user_id'), 'steam_tracking_states', ['discord_user_id'], unique=False)
    op.add_column('game_sessions', sa.Column('source', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('game_sessions_discord_user_id_fkey'), 'game_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'game_sessions', 'users', ['discord_user_id'], ['discord_user_id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('steam_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_steam_id'), 'users', ['steam_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_steam_id'), table_name='users')
    op.drop_column('users', 'steam_id')
    op.drop_constraint(None, 'game_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('game_sessions_discord_user_id_fkey'), 'game_sessions', 'users', ['discord_user_id'], ['discord_user_id'])
    op.drop_column('game_sessions', 'source')
    op.drop_index(op.f('ix_steam_tracking_states_discord_user_id'), table_name='steam_tracking_states')
    op.drop_table('steam_tracking_states')
    # ### end Alembic commands ###
